### ISSUE TITLE
Support elm-css's property function

### ISSUE THREAD

**Issue by sean-clayton** [SentiaAnalytics/bs-css#107]
elm-css supports letting users embed any CSS declaration with an api like such:

```elm
property "grid-template-areas" """
  "header header header"
  "sidebar content content"
  "footer footer footer"
"""

property "grid-area" "content"
```

It's a nice escape hatch for when properties or values don't have type definitions so users can sacrifice a little type-safety to not be blocked by lack of existing definitions in the library.

I looked at the source and [it seems the `d` function already does this](https://github.com/SentiaAnalytics/bs-css/blob/cdd004f2fb735060bc4489bb2f061ffc998c62ae/src/Css.re#L343), but isn't exposed in `Css.rei`--I could maybe create a PR, but I'm not quite sure how to test it all.

The elm-css implementation:

https://github.com/rtfeldman/elm-css/blob/8d0e7c1a1affb500f014c010efd71b91356be9ac/src/Css.elm#L7243-L7246

**Comment by giraud** [comment]
it's already possible.
The `d` function is not exposed in the interface, but the `unsafe` function is (https://github.com/SentiaAnalytics/bs-css/blob/master/src/Css.re#L612 : it is an alias to `d`) .
you can write `unsfafe("property", "value")` with property and value being whatever you want.

**Comment by sean-clayton** [comment]
@giraud Ah, I thought I looked everywhere—apparently I didn't! That worked perfectly, thanks for that! I'm not sure how much of a problem y'all might think it is, but do you think there is a way to maybe point that out for people who also didn't notice this right away? In any case, I'll go ahead and close since if that request is a valid issue I don't think it belongs here.

**Comment by giraud** [comment]
@sean-clayton maybe you could do a pr to update the README with that missing point ?

**Comment by sean-clayton** [comment]
@giraud I definitely could! I'll see what I can muster up :)

**Comment by sean-clayton** [comment]
@giraud Done! #110
