### ISSUE TITLE
support :not css pseudoselector for complex selection

### ISSUE THREAD

**Issue by lewisf** [SentiaAnalytics/bs-css#112]
I'm not sure if I'm missing something, but I'm struggling to find out how to do the equivalent of

```
div > *:not(:first-child)::before {
}
```

is there a way to get the `not` pseudo selector?

**Comment by giraud** [comment]
the selector api is limited, it might be easier to create the selector directly:
`Css.style([ selector(" > *:not(:first-child)::before", [ ... ]) ])`

**Comment by lewisf** [comment]
Thanks, good to know!
