### ISSUE TITLE
Support Nested Selector

### ISSUE THREAD

**Issue by muhammadridho** [SentiaAnalytics/bs-css#115]
is this support for nested selector like `emotion` do it ?, for example i want a generate like this ?
  
```
color: turquoise;

  a {
    border-bottom: 1px solid currentColor;
    cursor:pointer;
  }
```

if there is another way, please tell me, thanks

**Comment by wegry** [comment]
Hey @muhammadridho, I asked this very question [here](https://stackoverflow.com/q/53105205/1924257). The gist is that the `selector` function allows you to do this.
