### ISSUE TITLE
Flexbox: `justify-content: "space-evenly"`

### ISSUE THREAD

**Issue by rjhilgefort** [SentiaAnalytics/bs-css#117]
Is there a reason why "justifyContent(`spaceEvenly)" is missing from the Flexbox implementation? Is it hard to add?

**Comment by wegry** [comment]
Probably just hasn't been added yet. Feel free to submit a PR. 

https://github.com/SentiaAnalytics/bs-css/blob/master/src/Css.re#L976
https://github.com/SentiaAnalytics/bs-css/blob/master/src/Css.rei#L585

are in the neighborhood of where you would need to put it.

**Comment by rjhilgefort** [comment]
@lucasweng I just forked and started to add this to find that you just put a PR in 26 minutes ago (#120 ). Thanks!

**Comment by lucasweng** [comment]
@wegry I forgot to add the value `spaceEvenly' to the interface 😅 , so it's not working really. I'll submit another PR to fix it and add a test for it

https://github.com/SentiaAnalytics/bs-css/blob/master/src/Css.re#L582
https://github.com/SentiaAnalytics/bs-css/blob/master/src/Css.rei#L354

**Comment by giraud** [comment]
fixed in 8.0.2
