### ISSUE TITLE
Support for "direction" property

### ISSUE THREAD

**Issue by contrastBro** [SentiaAnalytics/bs-css#131]
Hello,

is the css property "direction" supported? Failed to find it in Css.rei.

https://developer.mozilla.org/en-US/docs/Web/CSS/direction

**Comment by JakubMarkiewicz** [comment]
Not supported, i can make a quick PR for that :)

**Comment by JakubMarkiewicz** [comment]
It's merged, we can close it :)

**Comment by giraud** [comment]
Fixed in 9.0.1
