### ISSUE TITLE
(top, bottom, left, right) properties should also belong to the 'cascading' type

### ISSUE THREAD

**Issue by AlvaroBernalG** [SentiaAnalytics/bs-css#138]
Hello Good people of bs-css.

I find myself trying to overwrite the property top with the "inherit" value but I am unable to do so, the reason being is that the type that the 'top' property is of type 'length' which doesn't contain 'inherit', 'unset' nor 'initial' values.

top definition:
<img width="334" alt="Screenshot 2019-06-05 at 15 25 54" src="https://user-images.githubusercontent.com/12004383/58964115-43017280-87a6-11e9-8fd8-bf25171faa0b.png">

length definition:

<img width="470" alt="Screenshot 2019-06-05 at 15 25 31" src="https://user-images.githubusercontent.com/12004383/58964146-557bac00-87a6-11e9-8bc0-21c05c1e0e44.png">

<img width="1673" alt="Screenshot 2019-06-05 at 15 27 55" src="https://user-images.githubusercontent.com/12004383/58964336-a095bf00-87a6-11e9-9b4d-f863ed5fa943.png">
Thanks

**Comment by AlvaroBernalG** [comment]
Hello Good people of bs-css.

I find myself trying to overwrite the property top with the "inherit" value but I am unable to do so, the reason being is that the type that the 'top' property expects is of 'length' which doesn't accept 'inherit', 'unset' nor initial values.

Thanks

**Comment by giraud** [comment]
Fixed in 9.0.1
