### ISSUE TITLE
Abstracting types

### ISSUE THREAD

**Issue by giraud** [SentiaAnalytics/bs-css#144]
Hi everyone, this is a question I have about the API.

I'm annoyed by the fact that the Css.rei interface is not really used to abstract real type to user and that we have a confusion between the types and the functions (constructors).

For example, this is how the angle type is defined:
```
type angle = [ | `deg(float) | `rad(float) | `grad(float) | `turn(float)];

let deg: float => [> | `deg(float)];
let rad: float => [> | `rad(float)];
let grad: float => [> | `grad(float)];
let turn: float => [> | `turn(float)];
```

So I can use `deg(10.) or deg(10.) indifferently.

Now, if I just change the .rei file to this:
```
type angle;

let deg: float => angle;
let rad: float => angle;
let grad: float => angle;
let turn: float => angle;
```

it still compiles without problems, and I now can only use the constructors (deg(10.)). For me, this implementation removes the unnecessary confusion between types and functions.

The problem with this notation is that it's not obvious which functions can be used for the angle, so we can create the angle module to encapsulate the type and the functions:

```
// Can be better documented
module Angle: {
  type t;
  let deg: float => t;
  let rad: float => t;
  let grad: float => t;
  let turn: float => t;
  let toString: t => string; // Now makes sense
};

type angle = Angle.t; // For backward compatibility ?

// Just aliases to module functions because it's easier for end user (backward compat)
let deg: float => t;
let rad: float => t;
let grad: float => t;
let turn: float => t;
```

Still compiles.
Pros:
- no confusion
- backward compatible (for function usage)
- can be nicely documented
- toString makes sense
- almost identical to re-css library

The drawback is that you don't have direct access to the types but it seems to me that it's better than before.

What do you think?

**Comment by lucasweng** [comment]
Hi @giraud

I find encapsulating the types and the functions (especially grouping toString) in modules makes the code more organized and readable. Also, only exposing the function interface avoids inconsistency.

**Comment by giraud** [comment]
I can't abstract types, but I've started the work to extract some definitions and avoid duplicating the toString functions in master.
