### ISSUE TITLE
Missing support for `grid-template-areas` and `grid-area` ?

### ISSUE THREAD

**Issue by drew887** [SentiaAnalytics/bs-css#156]
Hey howdy, this package is great! I'm new to reasonml but this package worked exactly as expected out of the box which is fantastic!!

Now being new I'm not sure if I've just missed these somewhere, but it looks like this package is missing support for `grid-template-areas` and `grid-area` properties?

Thanks, and sorry if I've just missed them :sweat_smile:

**Comment by giraud** [comment]
yes, they are missing.

**Comment by giraud** [comment]
Fixed in 10.0.0
