### ISSUE TITLE
ClassName passed as prop doesn't overwrite local styles

### ISSUE THREAD

**Issue by MargaretKrutikova** [SentiaAnalytics/bs-css#163]
When passing `className` built with `Css.style(...)` into a component that has its own className, the styles that come from the prop don't overwrite those defined in component. For example, let's say there is a component `Background`:
```reason
let make = (~className="") => {
  let redBgStyle = Css.(style([backgroundColor(red)]));
  <div className={redBgStyle ++ " " ++ className}>...</div>
};
```

Then in the parent component I want to overwrite its background color:
```reason
<Background className=Css.(style([backgroundColor(green)])) />
```

This won't overwrite the component's styles because the specificity of the rules from `className` prop is lower than the component's css.

`Emotion` exposes a function called [`cx`](https://emotion.sh/docs/emotion#cx), that should be used in this case to correctly overwrite styles. So this in the component will work:
```reason
  let redBgStyle = Css.(style([backgroundColor(red)]));
  <div className={Emotion.cx([|redBgStyle, className|])}>
};
``` 
The problem is that `bs-css` doesn't expose bindings for `Emotion`. Is there any way to include them (at least partially?) in the interface definition (`Css.rei`)?

**Comment by lucasweng** [comment]
Hi,

The [`merge`](https://github.com/SentiaAnalytics/bs-css#the-merge-method) method uses `cx` under the hood, so this in the `Background` example will work:
```reason
let make = (~className="") => {
  let redBgStyle = Css.(style([backgroundColor(red)]));
  <div className=Css.merge([redBgStyle, className])>...</div>
};
```

**Comment by MargaretKrutikova** [comment]
Oh, cool, thanks! Didn't realise that. Maybe it makes sense to add this specific example with passing `className` into a component and then using `merge` to safely overwrite component's styles?

I didn't get it from the docs, that you should use `merge` specifically for this scenario and was using `Cn.make` from `re-classnames` first, which didn't work so I spent quite some time researching why 😄

**Comment by giraud** [comment]
I think it's well explained in the github front page
