### ISSUE TITLE
Proposal: A better type system for values

### ISSUE THREAD

**Issue by glennsl** [SentiaAnalytics/bs-css#17]
I've been toying a bit with the type system to get value types to compose better. This will make declarations more concise, but will also solve some issues that I don't think can be solved with the current approach. AND I actually think the errors this produces is better.

### The problem

CSS is typed as lots of nested unions. These unions are currently modeled in one of two ways:

1. As string-backed abstract types, e.g. `cssunit`, `color`. These are efficient and concise, but do not nest and need to be uniquely named.
2. As ordinary vairants, e.g. `background`. These nest and do not need to be uniquely named, but are inefficient and verbose.

A common problem for both approaches is that they need to enumerate every single possible value of that type, which for 1. is practically impossible due to the need for unique names, and for 2. makes the implementation very verbose and repetitive.

More specifically, the practical problem is with implementing these CSS features:

1. The universal values, `inherit`, `initial` and `unset`, which should be appllicable to every css property.
2. Nested unions can become pretty verbose, either when used or when implemented (or a bit of both, as it is now). For example, a DRY implementation of `background ` would have usage look like `background(Image(Url(url("http://..."))))`. Alternatively it can be "flattened" to just`background(Url("http://..."))`, but at the cost of needing to explicitly enumerate and convert all possible values in the implementation of each property.

### Proposal

By using a phantom polymorphic variant type, we can model this more precisely.

This is what it could look like in use:

```rust
Css.(style([
  background(white),
  background(url("http://...")),
  background(linearGradient(...)),
  color(unset),
]));
```
Compared to today:
```rust
Css.(style([
  background(Color(white)),
  background(Image("http://...")),

  /* gradients currently aren't valid images, so including them would require adding another
   * level (which would also make the url declaration above more verbose), or alternatively
   * another variant constructor if flattened
   */
  background(Image(Gradient(linearGradient(...)))),

  /* not implemented today, but could be hacked together to look like this and be somewhat
   * type-safe
   */
  unset(color),
]));
```

Error would look like this:
![2017-12-18-120530_312x148_scrot](https://user-images.githubusercontent.com/5207036/34103218-4339e17e-e3ec-11e7-8ad3-bf17c96a7ebb.png)

#### Implementation

Time for magic. Let's first look at the interface:

```rust
  /* The type of all css values */
  type value('a);
  
  /* [`color] is the type of a polymorphic variant with a single constructor, `color */
  type color = value([`color]);
  let white: color;
  
  /* The aliases aren't strictly necessary, but gives nicer error messages */
  type url = value([`url]);
  let url: string => url;
  
  /* [< `color ...] means we'll accept any polymorphic variant type containing a subset of
   * these constructors. So value([`color]) is good, as would value([`color | `url]) be,
   * but not value([`color | `length])
   */
  type background('a) = value([< `color | `url | `gradient] as 'a);
  let background: background('a) => rule;
```

To implement it, we'll define a couple of helpers to avoid blind casting magic and ensure what we put in and get out are actually strings, as expected:

```rust
  external makeValue : string => value(_) = "%identity";
  external getValue : value(_) => string = "%identity";
```
We'll also represent the rule as just a tuple for simplicity:

```rust
type rule = (string, string);
```
And then the meat of the implementation:
```rust
  type value('a);
  
  type color = value([`color]);
  let white = makeValue("white");
  
  type url = value([`url]);  
  let url = url => makeValue({j|url($url)|j});
  
  type background('a) = value([< `color | `url | `gradient] as 'a);
  let background = value => ("background", getValue(value));
```

[A playground with this code, as well as an example of how to define a universal value](https://reasonml.github.io/try/?reason=LYewJgrgNgpgBAYQM5IFxwN4Cg5wC4CeADvAE7QwDcOcNA9AFRwAqAFgJZJydwB2MAYxgoAhqQL4Q3YEVjAYvPHAi92ANxikkIqHDU6IwgDT5WICAHNWfEEv5DRpdlAntepngDMQpYEZpMcABGEEoA7ux4ZqFwChDypCJ4bhZwOrpEICjsQbB6BsJwYawKcGAwnm5unsqqGlo6+VCGXFEwBAG4YeZQYLG8fRBEwTApRTAiANb4xPD6TiK5hSIDcPIwSm3cpPAgNVv6zWTCeE4CySDuDHQ0hCQzJFwAvHAA2jS4AD5wAAawvBYoh84N8fgIQFAfMDQRBSFAaABdai4RgsEoPXY1dJwAQoJotODXW6zfEwAAUAHIRABKOAvKk4y5IU4iNxKV4AHgxSARdLgVORtBRTFeYIhPl5PC2d0xaTgmRcoFIRA4AnyC0URUi1hEcCQKTy4N4zPI5x8JjFkNIhJuuBljKtfMOhjJovBVoR1MFsHCHDwMHQ7p8gvoTDY8B07BESGWO14FKUJvY5xcfEEwm04hMISUFnUhVUQmtmlIPjWGZEFkKRLtJNhuhezvJovrnu9G2UcPQSYBdIAfJ2oCHhW8uZaywA6Ke8+QrLhhGAUqC6EQCIREJQrCQKghKlXJ9VRzX2o14VmqXu6pAQIIxpR7D5MNoxxnG04QM1aCdwADKUibrrjqQnrcFwFggOAJjRkUPR9ABbritaMJwiBQQwP4uCEsEMS8LYpKAUGSG-P8gKsJ6j62hiwSrpMFilioYCUjSToFK6Y6ESCvz1pxPx0SIYDsAoeC8tBVJejQPrUQItH0QM6BBDRdHmAMTG0k8A7kLAw5wKiACCtT5g0uhNiYUQ8BEy4jGkRCyMmix5HgUhbvKpYkKQhA2hJHYqHe6AAQA+uJuBYAAvny2DBSOABiZb6jIUDJpEEgLkuug7EQOwxse6KaRGXAAFYQMycp4EMeQ1lRuV8mSPYWCYtXicS9wys8bzQsRCike1QHdfWiKCvaAFiXyDJGia57slyLW8vSIjaaif7yNIsgwPIihJOwlxwCUUBua0TlqCA7B9Lkbh9MAlYHisfQKNeOxFKwSTjPKMRuGkqxVveMRiPAtVcBVMAAB7+qQvCNBdkwwAAagUcDdqcYzqfhgV8gARAApMdQlJajgpAyDYO6J9MNHHDyNqQOtVo5j5SKDj2knohLFHARiFtl5vqRPALwQ9DrGo8UXOo0FQpUdxjasS2KFepFcCSeLg79msUx8yzGD5Z89ZkgAJPW1KfPlIUi018AKdJSkMapzMupyvwcchuignxAlCSJXBie2ShmzJyl9BLpNI2SqPexbAyoyYxOsU21LG7g8vGh2PMqyTLqoz5GzC9QIXUFgyBIBOZIRXAABS+eQqkAACFdST7luC-6IulxO5dwFXNeh4xWuo6weB4EQqB0HQU4TsLjdlyAlfVyHsmdwneCxzpTAlmWFWME3Ldt9PvtBwAxDA++Z0SRs56ihXFY5epmGE3B4BSXDMs4GQQruPj7mq11apZe7WGyTm8AQZlewEHMEUFYSgiSSWKEkGA9R0B5wnPBP4nUoggRePA9OeBKBAA)

### Conclusion

More testing is of course needed to ensure there aren't any problems when things get more complex, or if CSS does something super weird that doesn't fit this model either. But I think this approach is worth exploring further. If everything works out it's looking to be more concise, flexible, efficient and give better errors, but at the cost of making the implementation a bit harder to understand.

**Comment by cullophid** [comment]
This looks really cool, let's start a separate branch where we can try it out.

**Comment by cullophid** [comment]
I'll add you as a collaborator once I have put my daughter to bed

**Comment by glennsl** [comment]
Thanks! I'll try this out in a branch once I get some time.

**Comment by cullophid** [comment]
Great, I added you as a collaborator

**Comment by wokalski** [comment]
I suggest that those functions return `strings` (probably behind an opaque type) so that we don't have to run through conversion once again.

**Comment by cullophid** [comment]
@wokalski im not sure i follow?

**Comment by wokalski** [comment]
Sorry. Irrelevant. I thought I was writing this in another repo (bs-nice)

**Comment by cullophid** [comment]
Im closing the issue since i dont think its relevant after v6.0.0
