### ISSUE TITLE
lineHeight unit

### ISSUE THREAD

**Issue by kennetpostigo** [SentiaAnalytics/bs-css#19]
What unit to use for lineHeight? I'm trying to pass 1.3, but px requires whole numbers, what unit should be used? Not even sure if it should have been px as in css we don't add px to the end of the value.

**Comment by cullophid** [comment]
Currently lineHeight works on px/em/rem which is not really sensible.
You can use unsafe("lineHeight", "1.5") until we can release a fix

**Comment by kennetpostigo** [comment]
ok thanks

**Comment by maarekj** [comment]
Today, **lineHeight** has the type `float => rule`
But lineHeight is supposed to be able to receive pixel, rem, em etc., in addition to the float.

It would be better if **lineHeight** had the following type: ```[ lenght | `abs(float) ]```

**Comment by maarekj** [comment]
I just added a new issue #53
