### ISSUE TITLE
[Bug] `type css` is aliased to string

### ISSUE THREAD

**Issue by chenglou** [SentiaAnalytics/bs-css#21]
https://github.com/SentiaAnalytics/bs-css/blob/0a037cdc977c7d18a45a46bfd4cb506232e3a6a5/src/Css.re#L10

The actual type is an object: https://github.com/threepointone/glamor/blob/667b480d31b3721a905021b26e1290ce92ca2879/index.d.ts#L268

This causes the following bug: https://github.com/phenomic/phenomic/issues/1220

Where a style object is directly passed to className but it's not an actual string etc.

cc @thangngoc89

**Comment by thangngoc89** [comment]
Hey I'm sorry but isn't aliasing `type css = string` is a wrong binding?
