### ISSUE TITLE
backgroundPosition(align, [align])

### ISSUE THREAD

**Issue by bkonkle** [SentiaAnalytics/bs-css#26]
The current implementation of `backgroundPosition` looks like this:

```reason
let backgroundPosition = (x, y) =>
  d("backgroundPosition", string_of_length(x) ++ " " ++ string_of_length(y));
```

Unfortunately, this prevents things like `backgroundPosition: center;`. Is it possible to support `string_of_align()` here as well?

**Comment by cullophid** [comment]
`backgroundPosition(center)` is a shorthand  for `backgroundPosition(pct(50.), pct(50.))`
