### ISSUE TITLE
Compose

### ISSUE THREAD

**Issue by kennetpostigo** [SentiaAnalytics/bs-css#27]
Is there a good way to compose multiple styles?

**Comment by cullophid** [comment]
yes styles are just lists until you call `style` 
```
let blackButton = style([background(black), color(white), ...defaultButton]);

let customCard = style @@ List.append(customStyle, cardStyles);

```

once you call `style` the stylesheet is written to the dom, so you cant alter/extend it.
This is different from Glamor.js, but I feel that it provides a simpler API where its easy to reason about when the style tags are created.

I use a `Styles` module for each component


```
module Styles = {
   let title = style([color(black), fontSize(px(24))]);
   let item = isSelected => style([
     isSelected ? boxShadow(~y=px(4),  ~blue=px(15), rgba(0, 0, 0, 0.3) : boxShadow(~y=px(4),  ~blue=px(15), rgba(0, 0, 0, 0.3),
     ...defaultCard
  ]);
}
```

this way i know that the title styles are generated at load time, and only the card style is generated at runtime.
