### ISSUE TITLE
Colon-like infix operator

### ISSUE THREAD

**Issue by Ebuall** [SentiaAnalytics/bs-css#29]
I know most people don't like operators, but since it's DSL, I wanted to share idea.
We have this fat and ugly operator `( @@ )`, that is perfect for reducing number of parentheses on function call, so instead of this:
```reason
let card = style([
  display(flexBox),
  flexDirection(column), 
  alignItems(stretch),
  backgroundColor(white),
]); 
```
we get this:
```reason
let card = style([
  display @@ flexBox,
  flexDirection @@ column, 
  alignItems @@ stretch,
  backgroundColor @@ white,
]); 
```
Which looks a bit nicer, but far from perfect.
We can define a better operator, that behaves exactly like `( @@ )`, but looks more CSS-like and lightweight:
```javascript
let card = style([
  display^: flexBox,
  flexDirection^: column, 
  alignItems^: stretch,
  backgroundColor^: white,
]); 
```

We can define it like this:
```reason
let ( ^: ) = ( @@ );
```
Or like this:
```reason
external ( ^: ) : ('a => 'b) => 'a => 'b = "%apply";
```

**Comment by cullophid** [comment]
Thats makes sense...

**Comment by cullophid** [comment]
Im a little bit unsure if i like redefining an existing operator... reason is all about being easy for beginners, and i feel this might pull the other way...
If we embrace `@@` it might be a way for people to lean how to use it throughout their code.
