### ISSUE TITLE
[Question] Handling JS string color

### ISSUE THREAD

**Issue by DCKT** [SentiaAnalytics/bs-css#36]
Hello,

I'm asking myself about how to handle string color coming from the JavaScript side.
Is there an escape hatch for this ?

Thanks :)

**Comment by cullophid** [comment]
I'm not sure what you mean... Can you provide an example.

**Comment by DCKT** [comment]
Sure : 
```ocaml
module Styles = {
  open Css;
  let tag = (~tagColor: Js.Nullable.t(string)) => {
    let defaultColor =
      switch (Js.Nullable.toOption(tagColor)) {
      | None => hex("354052")
      | Some(customColor) => hex(customColor)
      };
    style([
      color(defaultColor),
    ]);
  };
};
```

`tagColor` come from React props so it could be anything `#fff` or `rgb(255,255,255)`. In this example I assume it's always a `hex`.

**Comment by cullophid** [comment]
You can use `unsafe`
```
let text = style([
  unsafe("color", colorString)
])
```

**Comment by cullophid** [comment]
If it is possible to move the css code from js to reason its probably a good idea

**Comment by DCKT** [comment]
It's exactly what I'm looking for ! Thanks @cullophid
