### ISSUE TITLE
Isn't the style call on render being executed at each render pass ?

### ISSUE THREAD

**Issue by geraldodev** [SentiaAnalytics/bs-css#46]
https://github.com/SentiaAnalytics/bs-css/blob/901534988d93f7c4695cc5a7a530e95abc253718/example/example.re#L31

**Comment by cullophid** [comment]
yes. Glamor does however check not to render the same values multiple times.

A better solution is to use a style module:
```
module Styles = {
  let page = style([ 
    background(palegoldenrod)
  ]);
}

<div className=Styles.page >
```

Now you are guaranteed that the styles are only rendered once

**Comment by cullophid** [comment]
I updated the example file to use a Style module instead... thanks for the heads up
