### ISSUE TITLE
What is the way of generating (min-width: 960px) with bs-css

### ISSUE THREAD

**Issue by geraldodev** [SentiaAnalytics/bs-css#47]
Hi folks,

I was using Css.media(string, Css.rule) and wanted to compute  (min-width: 960px) with bs-css.

Initially my thought was that was possible because internally we have string_of_length, we also have  minWidth. 
After trying a bit I did not found a way to do that.

Thank you for wrapping Glamor.

This is my first css in js (reason actually) experience.

**Comment by cullophid** [comment]
```
module Styles = {
  let container = style([
    media("(min-with: 960px)", [ ... ])
  ]);
} 
```

Its a primitive api atm. I still not quite sure how to implement media queries an a type safe way.

**Comment by cullophid** [comment]
I hope this helped
