### ISSUE TITLE
use 'unset' or 'inherit' values

### ISSUE THREAD

**Issue by giraud** [SentiaAnalytics/bs-css#49]
Hi, 
how can I use these special values ?
I want a `font-size: unset` rule, but I don't know how to do better than this: `style([unsafe("fontSize", "unset")])`.
I'm on bs-css@6.7.0
thanks

**Comment by cullophid** [comment]
There isnt good support for cascade, since it kinda breaks the idea of in component CSS. Can you maybe share your use case?

**Comment by cullophid** [comment]
I was simply explaining why i haven't added it. If it is important for your usecase you are more than welcome to submit a PR.
