### ISSUE TITLE
Can't use it as a library

### ISSUE THREAD

**Issue by giraud** [SentiaAnalytics/bs-css#50]
bs-css@6.7.0 is dependent on bs-platform@^3.0.0 but it is published with js files compiled with the 2.2.2 version.
The published js files are still using Pervasives.string_of_int that doesn't exist anymore in bs 3.3.0.
This is breaking my code when I use it in a transitive dependency.

**Comment by cullophid** [comment]
version 7.0.0 uses bs-platform 3.1.5
