### ISSUE TITLE
lineheight unit

### ISSUE THREAD

**Issue by maarekj** [SentiaAnalytics/bs-css#53]
Today, **lineHeight** has the type `float => rule`
But **lineHeight** is supposed to be able to receive pixel, rem, em etc., in addition to the float.

It would be better if **lineHeight** had the following type: ```[ lenght | `abs(float) ]```

**Comment by maarekj** [comment]
Yes with `unsafe("line-height", "15px")` but it is tricky

**Comment by cullophid** [comment]
I haven't had any issues with this yet, but if you believe its a necessary change you are welcome to open a PR :)

**Comment by giraud** [comment]
with 7.1 you can do `lineHeight(rem(1.3))`
