### ISSUE TITLE
Add fill and other properties for svg?

### ISSUE THREAD

**Issue by guilhermedecampo** [SentiaAnalytics/bs-css#54]
Hello! 👋 

Do you think is a good idea to add some props like fill, stroke for svg?

**Comment by cullophid** [comment]
They are in. Just under the SVG module.
```
let circle = style([
  SVG.fill(blue)
]);
```

**Comment by cullophid** [comment]
You are welcome to add more

**Comment by guilhermedecampo** [comment]
NIce thanks for pointing out! Maybe I was too tired and didn't see the module SVG. 👍
