### ISSUE TITLE
fontSize does not support absolute and relative sizes

### ISSUE THREAD

**Issue by uosl** [SentiaAnalytics/bs-css#55]
According to the [formal syntax for font-size](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size), it's supposed to support absolute and relative sizes like large, larger, etc.

Would you agree that bs-css needs types for absolute and relative sizes so that they can be supported by fontSize, or have you already thought through this?

I think typed css in reason has lots of potential, and that this project would flourish with more contributors and users. I'm still learning the language but I'll try and dedicate time to this.

**Comment by cullophid** [comment]
I have thought about it and I'm not sure if they are needed. Generally I think that modular CSS should not use relative units. When a component relies on context its harder to reuse.  If we come across a good use case it can ofc be added

**Comment by cullophid** [comment]
Right now we are trying out ideas and figuring out how typed CSS should work. I don't know the answer yet.
On some things bs-css might be too limiting and on other it is too loose.
Once we have learned more we will do a proper reason style breaking release :)

**Comment by uosl** [comment]
That makes sense. [=
I'll close the issue since I can't think of any good use cases for this. CSS is bad enough as it is!
