### ISSUE TITLE
Looking for (co)maintainers

### ISSUE THREAD

**Issue by cullophid** [SentiaAnalytics/bs-css#58]
First of all Thanks to everyone who are using and or contributing to bs-css!
I am sorry that it often takes a while before I get to answer issues, or review pull requests.
Between Baby and startup I dont have much time on my hands.

If any of you are using bs-css and would like to help maintain the project (answer issues, review/merge PR's) I would really appreciate it.
I will ofc still be here as much as i can.

**Comment by brad-decker** [comment]
@cullophid My company is going to be shifting towards Reason gradually over the next couple of quarters and we would love to help maintain this library if you don't mind some Reason/ocaml novices getting involved! I've opened a couple of PRs and would be willing to help stay on top of issues and maintain the package.

**Comment by giraud** [comment]
@cullophid I'd like to help you, sent a message in discord

**Comment by cullophid** [comment]
Hi Thank you very much... sorry i have been silent the last month.. i have been on vacation:)
Ill be catching up tonight and ill add you as contributors. Thank you for helping out.

**Comment by giraud** [comment]
That's great news, thank you
