### ISSUE TITLE
Support for `inherit` value

### ISSUE THREAD

**Issue by loganfromlogan** [SentiaAnalytics/bs-css#70]
Inherit is a useful value with properties like `borderRadius`, `borderColor`, `fontSize`, etc...

If there is a way to do this already, would you mind pointing me in the right direction?

**Comment by giraud** [comment]
See #49. The author of bs-css didn't like much that idea.
But the problem today is that this repo is no more maintained, PR are not merged. So you must use the unsafe function.
you can have some local code like:
`let inherit = x => unsafe(x, "inherit");`
and use it with:
`inherit("fontSize")`

**Comment by cullophid** [comment]
Hi sorry i have been absent.
I haven't added inherit values because i did not see the value when used for modular css.
That being said. bs-css is moving more towards "fully" implementing css and im open for PRs for these values

**Comment by thislogancall** [comment]
Awesome. And good to hear this is still maintained!!!

**Comment by giraud** [comment]
@loganfromlogan hey, why did you close it ?
