### ISSUE TITLE
Support for `content` property on pseudo elements (::after, ::before)

### ISSUE THREAD

**Issue by loganfromlogan** [SentiaAnalytics/bs-css#71]
I can't seem to find any way to assign a content property (empty string is what I'm going for) within a pseudo element.

If there is a way to do this already, would you mind pointing me in the right direction?

**Comment by alexeygolev** [comment]
@loganfromlogan we are using ``declaration(("content", " "))` for the time being but I wonder if there is a reason for not having it. Pretty commonly used feature. There might be a name clash as `content` binding is used for ``content` value alias for `flexBasis` type. So I'd wait for a comment from the maintainer before opening a PR.

**Comment by giraud** [comment]
I used `unsafe("content", " ")` in my project, but it's not the empty string.
I don't think there is a reason to not have it.

**Comment by giraud** [comment]
Added a contentRule to not break existing code

**Comment by giraud** [comment]
update to 7.2.0
