### ISSUE TITLE
boxSizing needs cascading values

### ISSUE THREAD

**Issue by baldurh** [SentiaAnalytics/bs-css#87]
Of course a lot of other properties need this as well, but right now I need it for `boxSizing`! 😄
I’m writing some base css for my app and want this rule:
`*, *::before, *::after { box-sizing: inherit; }`

I want to be able to do it cleanly like so:
``global("*, *::before, *::after", [boxSizing(`inherit)])``

But right now I have to do:
`insertRule("*, *::before, *::after { box-sizing: inherit; }")`

**Comment by giraud** [comment]
v7.4.0

**Comment by baldurh** [comment]
Sweet!
