### ISSUE TITLE
Need to be able to set pixels as floating point values

### ISSUE THREAD

**Issue by baldurh** [SentiaAnalytics/bs-css#88]
We’re creating a fluid grid system which requires floating point pixels since spacing and sizes are calculated values. What would be the best option? Changing `` `px`` to accept float would be a breaking change. So maybe adding `` `pxFloat``?

**Comment by baldurh** [comment]
That doesn’t solve anything. I need to assign the floating point value as the actual pixel value. Otherwise I lose information during calculation and end up with offset pixels

**Comment by giraud** [comment]
v7.5.0
